Added Quicksort in C++ fixes issue #12 .
nikochiko/cool-algos pull request #44
Opened 2020-10-01 11:43 UTC by Roshan13046

Issue no #12  fixed.
Quicksort algorithm in c++ added.
Please check.
Thank you.

2020-10-02 16:09 UTC, nikochiko requested changes
Nice work! Few small changes and this will be ready to go.
Apart from the mentioned comment, also change the filename from `quick_sort.cpp.cpp` to `quick_sort.cpp`.

2020-10-02 16:09 UTC, nikochiko commented on Sorting/quick_sort/quick_sort.cpp.cpp
> +
Can we take this input from STDIN.
First line: N - number of inputs
Second line: N space-separated integers

for example, 
```
5
2 5 23 14 4
```

2020-10-02 19:36 UTC, Roshan13046 commented
> Nice work! Few small changes and this will be ready to go.
> Apart from the mentioned comment, also change the filename from `quick_sort.cpp.cpp` to `quick_sort.cpp`.

Sure.

2020-10-03 06:13 UTC, nikochiko approved these changes
Great job! :+1:

2020-10-03 07:00 UTC, Roshan13046 commented
> Great job! 👍

Thanks.

2020-10-23 12:17 UTC, nikochiko commented
merged restyled version - https://github.com/nikochiko/cool-algos/pull/45. thanks for contributing

2020-10-23 12:17 UTC, closed without merging